export const SUGGESTED_PEOPLE = "Suggested People";
export const OTHER_PEOPLE = "All Other People";
export const FALLBACK_PAGE_ERROR_MESSAGE = "Ooops! Nothing here...";
export const COMPANY_NAME = "Flashback Inc.";
export const YEAR = "2024";
export const ALL_RIGHTS_RESERVED = "All right reserved";
export const CONTACT = "Contact:";
export const PHONE_NUMBER = "+91 9090401234"
export const EMAIL = "team@flashback.inc";